Controllers/EmployeeController.cs
using AutoMapper;
using BLL.Interfaces;
using DAL.Entities;
using Demo.PL.Utility;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
	[Authorize]
	public class EmployeeController : Controller
	{
		private readonly IUnitOfWork unitofwork;
		private readonly IMapper mapper;

		public EmployeeController(IUnitOfWork _unitofwork, IMapper _mapper)
		{
			unitofwork = _unitofwork;
			mapper = _mapper;
		}

		public async Task<IActionResult> Index(string? searchvalue)
		{
			if (string.IsNullOrEmpty(searchvalue))
			{
				var employees = await unitofwork.EmployeeRepository.GetAllAsync();
				if (employees is null) return NotFound();

				var mapedemp = mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employees);
				
				return View(mapedemp);
			}
			var res = await unitofwork.EmployeeRepository.SearchByName(searchvalue);
			if (res is null)
				return NotFound();

			var mapedemployees = mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(res);
			//ViewBag.SearchValue = mapedemployees;// I'm not remember way i put this line here
			return View(mapedemployees);
		}
		[HttpGet]
		public async Task<IActionResult> Create()
		{
			ViewBag.Departments = await unitofwork.DepartmentRepository.GetAllAsync();
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Create(EmployeeViewModel employee)
		{
			if (ModelState.IsValid)
			{
				try
				{
					employee.ImageName = DocumentSetting.UploadFile(employee.Image, "Images");
					var mapedemployee = mapper.Map<EmployeeViewModel, Employee>(employee);

					await unitofwork.EmployeeRepository.AddAsync(mapedemployee);
					await unitofwork.CompleteAsync();
					TempData["Message"] = "Employee Created Successfully";
				}
				catch (Exception e)
				{
					ModelState.AddModelError(string.Empty, e.Message);
				}
				return RedirectToAction(nameof(Index));
			}

			return View(employee);
		}
		[HttpGet]
		public async Task<IActionResult> Details(int? id)
		{
			if (id is not null)
			{
				var employee = await unitofwork.EmployeeRepository.GetByIdAsync(id.Value);
				if (employee is not null)
				{
					return View(mapper.Map<Employee, EmployeeViewModel>(employee));
				}
				return NotFound();
			}
			return BadRequest();
		}
		[HttpGet]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id is null) return BadRequest();

			var employee = await unitofwork.EmployeeRepository.GetByIdAsync(id.Value);
			if (employee is null) { return NotFound(); }
			TempData["ImageName"] = employee.ImageName;
			var departments = await unitofwork.DepartmentRepository.GetAllAsync();
			ViewBag.Departments = mapper.Map<IEnumerable<Department>, IEnumerable<DepartmentViewModel>>(departments);
			return View(mapper.Map<Employee, EmployeeViewModel>(employee));
		}
		[HttpPost]
		public async Task<IActionResult> Edit(EmployeeViewModel employee, [FromRoute] int? id)
		{
			if (id is null || id != employee.Id) { return BadRequest(); }
			try
			{
				string ImageName = TempData["ImageName"] as string;
				if(ImageName is not null)
				{
					DocumentSetting.DeleteFile("Images", ImageName);
				}
				employee.ImageName = DocumentSetting.UploadFile(employee.Image, "Images");
				var mapedemployee = mapper.Map<EmployeeViewModel, Employee>(employee);
				unitofwork.EmployeeRepository.Update(mapedemployee);
				await unitofwork.CompleteAsync();
				TempData["Message"] = "Employee Updated Successfully";
			}
			catch (Exception e)
			{
				ModelState.AddModelError(string.Empty, e.Message);
			}
			return RedirectToAction(nameof(Index));
		}
		[HttpGet]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id is null) return BadRequest();
			var employee = await unitofwork.EmployeeRepository.GetByIdAsync(id.Value);
			if (employee is null) { return NotFound(); }
			TempData["ImageName"]=employee.ImageName;
			return View(mapper.Map<Employee, EmployeeViewModel>(employee));
		}
		[HttpPost]
		public async Task<IActionResult> Delete(EmployeeViewModel employee)
		{
			if (!ModelState.IsValid) { return BadRequest(); }
			try
			{
				var mapedemployee = mapper.Map<EmployeeViewModel, Employee>(employee);
				unitofwork.EmployeeRepository.Delete(mapedemployee);
				await unitofwork.CompleteAsync();
				DocumentSetting.DeleteFile("Images", TempData["ImageName"]as string);
				TempData["Message"] = "Employee Deleted Successfully";
				return RedirectToAction(nameof(Index));

			}
			catch (Exception e)
			{
				ModelState.AddModelError(string.Empty, e.Message);
			}
			return RedirectToAction(nameof(Index));
		}
	}
}

Controllers/RolesController.cs
using AutoMapper;
using DAL.Entities;
using DAL.Models;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
	[Authorize(Roles = "Admin")]
	//[Authorize(Email ="sharawym275@gmail.com")]
	public class RolesController : Controller
	{
		private readonly RoleManager<IdentityRole> rolemanager;
		private readonly IMapper mapper;
		private readonly UserManager<ApplicationUser> usermanager;
		public RolesController(RoleManager<IdentityRole> _rolmanager, IMapper _mapper,UserManager<ApplicationUser> _usermanager)
		{
			rolemanager = _rolmanager;
			mapper = _mapper;
			usermanager = _usermanager;
		}

		public async Task<IActionResult> Index(string email)
		{
			if (string.IsNullOrEmpty(email))
			{
				// convert all usere ---> userviewmodel

				var roles = await rolemanager.Roles.ToListAsync();
				var mapedrole = mapper.Map<IEnumerable<IdentityRole>,IEnumerable<RoleViewModel>>(roles);
				return View(mapedrole);
			}
			var role = (await rolemanager.FindByNameAsync(email));
			if (role is null) return View(Enumerable.Empty<RoleViewModel>());

			var maped = mapper.Map<IdentityRole,RoleViewModel>(role);
			
			return View(new List<RoleViewModel>() { maped });
		}
		//                                                          default value
		public async Task<IActionResult> Details(string id, string viewname = "Details")
		{
			if (string.IsNullOrEmpty(id)) { return BadRequest(); }

			var role = await rolemanager.FindByIdAsync(id);
			if (role is null) return NotFound();

			var maped = mapper.Map<IdentityRole, RoleViewModel>(role);
			return View(viewname, maped);
		}
		[HttpGet]
		public async Task<IActionResult> Edit(string id)
		{
			return await Details(id, nameof(Edit));
		}

		[HttpPost]
		public async Task<IActionResult> Edit(RoleViewModel model, string id)
		{
			if (model.Id != id || id is null) return BadRequest();
			if (!ModelState.IsValid)
			{
				return View(model);
			}
			try
			{
				var role = await rolemanager.FindByIdAsync(id);
				if (role is null) return NotFound();
				role.Name = model.Name;

				await rolemanager.UpdateAsync(role);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception e)
			{
				ModelState.AddModelError(string.Empty, e.Message);
			}
			return View(model);
		}

		[HttpGet]
		public async Task<IActionResult> Delete(string id)
		{
			return await Details(id, nameof(Delete));
		}
		[HttpPost]
		public async Task<IActionResult> ConfermDelete(RoleViewModel model)
		{
			if (!ModelState.IsValid) return BadRequest();
			try
			{
				var role = await rolemanager.FindByIdAsync(model.Id);
				if (role is null) return NotFound();
				await rolemanager.DeleteAsync(role);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception e)
			{
				ModelState.AddModelError(string.Empty, e.Message);
			}
			return View();
		}
		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Create(RoleViewModel model)
		{
			if (ModelState.IsValid)
			{
				var maped = mapper.Map<RoleViewModel,IdentityRole>(model);

				var res = await rolemanager.CreateAsync(maped);
				if (res.Succeeded) return RedirectToAction(nameof(Index));

				foreach (var i in res.Errors)
					ModelState.AddModelError(string.Empty, i.Description);
			}
			return View(model);
		}

		[HttpGet]
		public async Task<IActionResult> AddOrRemoveUser(string roleId)
		{
			var role = await rolemanager.FindByIdAsync(roleId);
			if (role is null) return NotFound();

			var usersinrole = new List<UsersInRoleViewModel>();
			var users = await usermanager.Users.ToListAsync();

			foreach (var user in users)
			{
				usersinrole.Add(new UsersInRoleViewModel
				{
					Id = user.Id,
					Name = user.UserName,
					IsInRole = await usermanager.IsInRoleAsync(user, role.Name),// have bool value true or false
				}) ;
			}
			ViewBag.RoleId = roleId;
			return View(usersinrole);
		}

		[HttpPost]
		public async Task<IActionResult> AddOrRemoveUser(string roleId,List<UsersInRoleViewModel> users)
		{
			var role = await rolemanager.FindByIdAsync(roleId);
			if (role is null) return NotFound();

			if(ModelState.IsValid)
			{
				foreach (var user in users)
				{
					var userbeforeidt = await usermanager.FindByIdAsync(user.Id);
					if(ModelState.IsValid)
					{

						bool RoleIsFound = await usermanager.IsInRoleAsync(userbeforeidt, role.Name);
						if (user.IsInRole == true && !RoleIsFound)
						{
							await usermanager.AddToRoleAsync(userbeforeidt, role.Name);
						}
						else if (user.IsInRole == false && RoleIsFound)
						{
							await usermanager.RemoveFromRoleAsync(userbeforeidt, role.Name);
						}

					}
				}

				return RedirectToAction(nameof(Edit),new {Id= roleId });

			}
			return View(users);
		}
	}
}


Controllers/UsersController.cs
using AutoMapper;
using DAL.Models;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace Demo.PL.Controllers
{
	[Authorize]
	public class UsersController : Controller
	{
		private readonly RoleManager<IdentityRole> rolmanager;
		private readonly UserManager<ApplicationUser> usermanager;
		private readonly IMapper mapper;
		public UsersController(UserManager<ApplicationUser> _usermanager, IMapper _mapper, RoleManager<IdentityRole> _rolmanager)
		{
			usermanager = _usermanager;
			mapper = _mapper;
			rolmanager = _rolmanager;
		}
		public async Task<IActionResult> Index(string email)
		{
			if (string.IsNullOrEmpty(email))
			{
				// convert all usere ---> userviewmodel

				var users = await usermanager.Users.Select(u => new UserViewModel
				{
					Id = u.Id,
					FirstName = u.FirstName,
					LastName = u.LastName,
					Email = u.Email,
					PhoneNumber = u.PhoneNumber,
					Roles = usermanager.GetRolesAsync(u).Result
				}).ToListAsync();

				#region Add-Admin Role
				//for(int i=0;i<users.Count();i++)
				//{
				//	if (users[i].Email== "sharawym275@gmail.com")
				//	{
				//		var RolesList=users[i].Roles.ToList();
				//		if (!RolesList.Contains("Admin"))
				//		{
				//			RolesList.Add("Admin");
				//			users[i].Roles=RolesList;
				//		}
				//	}
				//} 
				#endregion

				return View(users);
			}
			var user = await usermanager.FindByEmailAsync(email);

			if (user is null) return View(Enumerable.Empty<UserViewModel>());

			var maped = new UserViewModel
			{
				Id = user.Id,
				FirstName = user.FirstName,
				LastName = user.LastName,
				Email = user.Email,
				PhoneNumber = user.PhoneNumber,
				Roles = usermanager.GetRolesAsync(user).Result

			};
			return View(new List<UserViewModel> { maped });
		}
		//                                                          default value
		[HttpGet]
		public async Task<IActionResult> Details(string? id, string viewname = "Details")
		{
			if (string.IsNullOrEmpty(id)) { return BadRequest(); }

			var user = await usermanager.FindByIdAsync(id);
			if (user is null) return NotFound();

			var maped = mapper.Map<ApplicationUser, UserViewModel>(user);
			maped.Roles = await usermanager.GetRolesAsync(user);
			return View(viewname, maped);
		}
		[HttpGet]
		public async Task<IActionResult> Edit(string id)
		{
			return await Details(id, nameof(Edit));
		}

		[HttpPost]
		public async Task<IActionResult> Edit(UserViewModel model,[FromRoute] string id)
		{
			if ( id is null ||model.Id != id) return BadRequest();
			if (!ModelState.IsValid)
			{
				return View(model);
			}
			try
			{
				var user = await usermanager.FindByIdAsync(id);
				if (user is null) return NotFound();
				user.FirstName = model.FirstName;
				user.LastName = model.LastName;
				user.PhoneNumber = model.PhoneNumber;

				await usermanager.UpdateAsync(user);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception e)
			{
				ModelState.AddModelError(string.Empty, e.Message);
			}
			return View(model);
		}

		[HttpGet]
		public async Task<IActionResult> Delete(string id)
		{
			return await Details(id, nameof(Delete));
		}
		[HttpPost]
		public async Task<IActionResult> Delete(UserViewModel model,[FromRoute]string id)
		{
			if(model.Id != id || id is null) { return BadRequest(); }
			if (!ModelState.IsValid)
			{
				return View(model);
			}
				var user = await usermanager.FindByIdAsync(id);
			if (user is null) return NotFound();

			try
			{
				await usermanager.DeleteAsync(user);
				return RedirectToAction(nameof(Index));
			}catch(Exception e)
			{
				ModelState.AddModelError(string.Empty,e.Message);
				return RedirectToAction("Error", nameof(HomeController));
			}
		}
		
	}
}

Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="application/x-javascript">addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); }</script>
    <!-- Custom Theme files -->
    <link href="~/css/AuthStyleSheet.css" rel="stylesheet" type="text/css" media="all" />
    <!-- //Custom Theme files -->
    <!-- Web Font -->
    <link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
    <link href="~/css/AuthStyleSheet.css" />
    <!-- //Web Font -->
</head>
<body>
    <!-- Main Content -->
    <div class="main-w3layouts wrapper">
        <h1>@ViewData["Title"]</h1>
        @RenderBody();
        <!-- Copyright -->
        <div class="colorlibcopy-agile">
            <p>&copy; @DateTime.Now.Year Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
        </div>
        <!-- //Copyright -->
        <ul class="colorlib-bubbles">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	@await RenderSectionAsync("validation", required: true)
</body>
</html>

Views/Shared/_ButtonsPartialView.cshtml
@model string
<td><a asp-action="Details" asp-route-id="@Model"><i class="fas fa-eye btn btn-info"></i></a></td>
<td><a asp-action="Edit" asp-route-id="@Model"><i class="fas fa-edit btn btn-warning"></i></a></td>
<td><a asp-action="Delete" asp-route-id="@Model"><i class="fas fa-trash-alt btn btn-danger"></i></a></td>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Demo.PL</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
	<!--font Aowsem libirary line to details and update and delete int the tables -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
		  integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
		  crossorigin="anonymous" referrerpolicy="no-referrer" />
	<style>
		body {
			/* Set background color to black */
			background-color: black;
			/* Set text color to white */
			color: white;
			/* Optional: Add background image or gradient */
			background-image: linear-gradient(to bottom right, #90eeee90, #90ee90);
			background-size: cover;
			background-position: center;
			background-repeat: no-repeat;
			background-attachment: fixed;
			/* Set min-height to 100vh for full viewport height */
			min-height: 100vh;
		}

		/* Custom styles for content container */
		.content-container {
			padding: 20px;
		}

		/* Additional styles can be added as needed */
	</style>
</head>
<body >
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.PL</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" style="font-family: Serif Fonts">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
						</li>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
						</li>
						
						</li>
						<li class="nav-item ml-auto" style="bading: 5px">
							<a class="nav-link text-danger " asp-area="" asp-controller="Account" asp-action="SignOut">SIGN OUT</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2024 - Demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("ClientSidValidation", required: false)@*call validation in every page*@
</body>
</html>